-- Create the comments table
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  post_id BIGINT NOT NULL REFERENCES posts(id)
);

-- Enable Row Level Security (RLS) on the comments table
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow read access to all rows for all users
CREATE POLICY "Allow read access to comments"
  ON comments
  FOR SELECT
  USING (true);
